# Generated by Django 2.0 on 2018-01-02 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_month', models.IntegerField(default=2)),
                ('max_day', models.IntegerField(default=2)),
                ('account_sid', models.CharField(default='AC8acd164ef4c16be2', max_length=50)),
                ('account_token', models.CharField(default='f8b6dc4bc9b7c39e7a6', max_length=50)),
                ('default_number', models.CharField(default='+5696459', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1600)),
                ('number_from', models.CharField(max_length=15)),
                ('number_to', models.CharField(max_length=15)),
                ('status', models.CharField(blank=True, max_length=500)),
                ('sid', models.CharField(blank=True, max_length=50)),
                ('error_code', models.IntegerField(blank=True, choices=[(1, 'Error en datos de reemplazos'), (2, 'Error en valores de reemplazos'), (3, 'Error en valores de reemplazos y datos'), (4, 'Error servicio de envió de sms'), (5, 'Error el texto no puede superar los 1600 caracteres')], default=None, null=True)),
                ('error_detail', models.CharField(blank=True, max_length=200, null=True)),
                ('deliver_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smstor.ConfigSMS')),
            ],
        ),
    ]
